[package]
name = "concat-idents"
version = "1.0.0"
authors = ["Dzenan Jupic <info@dzenanjupic.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0.30", features = ["full", "visit-mut"] }
quote = "1.0.6"

[dev-dependencies]
trybuild = "1.0.31"
